spring:
  h2.console.enabled: true
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
#    url: jdbc:h2:file:./4opeenrij
    url: jdbc:h2:mem:testdb

